CREATE TABLE usuario (
id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
nome varchar(100)  NOT NULL, 
email varchar(100) NOT NULL, 
senha varchar(254) NOT NULL, 
mao_de_obra decimal(10,2) DEFAULT 0 CHECK (MAO_DE_OBRA >= 0) NOT NULL)


CREATE TABLE unidade_medida(
id_unidade integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,  
nome varchar(100) NOT NULL, 
sigla varchar(10) NOT NULL)


CREATE TABLE categoria (
id_categoria integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
nome varchar(50)  NOT NULL,
id_usuario integer,

CONSTRAINT fk_categoria_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario))



CREATE TABLE insumo (
id_insumo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, 
nome varchar(100) NOT NULL, 
custo decimal(10,2) CHECK (custo >= 0) NOT NULL,
id_usuario INTEGER,
id_unidade INTEGER,

CONSTRAINT fk_insumo_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
CONSTRAINT fk_insumo_unidade FOREIGN KEY (id_unidade) REFERENCES unidade_medida(id_unidade))



CREATE TABLE produto (
id_produto integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
nome varchar(100) NOT NULL, 
margem_lucro decimal(5,2) CHECK (MARGEM_LUCRO  >= 0) NOT NULL, 
tempo_producao integer NOT NULL, 
custo decimal(10,2) DEFAULT 0 CHECK (custo >= 0) NOT NULL, 
preco_sugerido decimal(10,2) DEFAULT 0 CHECK (PRECO_SUGERIDO >= 0)  NOT NULL,
id_categoria integer,
id_usuario integer,


CONSTRAINT fk_produto_categoria FOREIGN KEY (id_categoria) REFERENCES categoria(id_categoria),
CONSTRAINT fk_produto_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario))

CREATE TABLE composicao_produto (
id_composicao integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, 
quantidade decimal(10,3) CHECK (QUANTIDADE >= 0)NOT NULL,
id_produto integer,
id_insumo integer,
id_unidade integer,

CONSTRAINT fk_composicao_produto FOREIGN KEY (id_produto) REFERENCES produto(id_produto),
CONSTRAINT fk_composicao_insumo FOREIGN KEY (id_insumo) REFERENCES insumo(id_insumo),
CONSTRAINT fk_composicao_unidade FOREIGN KEY (id_unidade) REFERENCES unidade_medida(id_unidade))


-- ADICIONAR CAMPO ATIVO
ALTER TABLE USUARIO
ADD ATIVO integer DEFAULT 1 NOT NULL

-- ADICIONAR CAMPO DE TENTATIVAS
ALTER TABLE USUARIO
ADD TENTATIVAS_LOGIN INTEGER DEFAULT 0 NOT NULL

CREATE TABLE HISTORICO_SENHA (
    ID_HISTORICO INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    SENHA VARCHAR(254) NOT NULL,

    CONSTRAINT FK_HISTORICO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO))
    

