-- =====================================================
-- 1. TABELA USUARIO
-- =====================================================

-- Armazena os dados dos usuários cadastrados.
-- Cada usuário possui um identificador único.

CREATE TABLE usuario (

    -- Identificador único do usuário.
    -- INTEGER: armazena números inteiros.
    -- GENERATED BY DEFAULT AS IDENTITY: gera o ID automaticamente.
    -- PRIMARY KEY: identifica cada registro.
    -- NOT NULL: não permite valores nulos.
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,

    -- Nome completo do usuário.
    -- VARCHAR(100): permite até 100 caracteres.
    nome VARCHAR(100) NOT NULL,

    -- E-mail utilizado para cadastro e login.
    email VARCHAR(100) NOT NULL,

    -- Armazena o hash da senha gerado pelo Bcrypt.
    -- A senha original não fica armazenada.
    senha VARCHAR(254) NOT NULL,

    -- Valor da mão de obra do usuário.
    -- DECIMAL(10,2): até 10 dígitos, sendo 2 decimais.
    -- DEFAULT 0: utiliza zero quando nenhum valor é informado.
    -- CHECK: impede valores negativos.
    mao_de_obra DECIMAL(10,2) DEFAULT 0
        CHECK (mao_de_obra >= 0) NOT NULL
)


-- =====================================================
-- 2. TABELA UNIDADE_MEDIDA
-- =====================================================

-- Armazena as unidades utilizadas nos insumos.
-- Exemplos: quilograma (kg), grama (g), litro (L).

CREATE TABLE unidade_medida (

    -- Identificador único da unidade.
    id_unidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,

    -- Nome da unidade de medida.
    -- Exemplo: Quilograma.
    nome VARCHAR(100) NOT NULL,

    -- Abreviação da unidade.
    -- Exemplo: kg.
    sigla VARCHAR(10) NOT NULL
)


-- =====================================================
-- 3. TABELA CATEGORIA
-- =====================================================

-- Organiza os produtos em categorias.
-- Exemplos: Bolos, Doces e Salgados.

CREATE TABLE categoria (

    -- Identificador único da categoria.
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,

    -- Nome da categoria.
    nome VARCHAR(50) NOT NULL,

    -- Identifica o usuário relacionado à categoria.
    id_usuario INTEGER,

    -- FOREIGN KEY: cria uma chave estrangeira.
    -- REFERENCES: indica a tabela e o campo relacionados.
    -- Relaciona a categoria ao usuário.
    CONSTRAINT fk_categoria_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
)


-- =====================================================
-- 4. TABELA INSUMO
-- =====================================================

-- Armazena os materiais utilizados na produção.
-- Exemplos: farinha, açúcar, leite e chocolate.

CREATE TABLE insumo (

    -- Identificador único do insumo.
    id_insumo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,

    -- Nome do insumo.
    nome VARCHAR(100) NOT NULL,

    -- Custo do insumo.
    -- CHECK impede que o custo seja negativo.
    custo DECIMAL(10,2) CHECK (custo >= 0) NOT NULL,

    -- Identifica o usuário responsável pelo insumo.
    id_usuario INTEGER,

    -- Identifica a unidade de medida do insumo.
    id_unidade INTEGER,

    -- Relaciona o insumo ao usuário.
    CONSTRAINT fk_insumo_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario),

    -- Relaciona o insumo à unidade de medida.
    CONSTRAINT fk_insumo_unidade
        FOREIGN KEY (id_unidade)
        REFERENCES unidade_medida(id_unidade)
)

-- =====================================================
-- 5. TABELA PRODUTO
-- =====================================================

-- Armazena os produtos fabricados pelo usuário.
-- Permite registrar custos, margem de lucro,
-- tempo de produção e preço sugerido.

CREATE TABLE produto (

    -- Identificador único do produto.
    id_produto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,

    -- Nome do produto.
    nome VARCHAR(100) NOT NULL,

    -- Margem de lucro desejada.
    -- DECIMAL(5,2): permite 5 dígitos, sendo 2 decimais.
    -- CHECK impede valores negativos.
    margem_lucro DECIMAL(5,2)
        CHECK (margem_lucro >= 0) NOT NULL,

    -- Tempo necessário para produzir o produto.
    -- INTEGER: armazena um número inteiro.
    -- A unidade de tempo deve ser definida pelo sistema.
    tempo_producao INTEGER NOT NULL,

    -- Custo total de produção.
    -- DEFAULT 0: valor inicial zero.
    custo DECIMAL(10,2) DEFAULT 0
        CHECK (custo >= 0) NOT NULL,

    -- Preço de venda sugerido pelo sistema.
    preco_sugerido DECIMAL(10,2) DEFAULT 0
        CHECK (preco_sugerido >= 0) NOT NULL,

    -- Identifica a categoria do produto.
    id_categoria INTEGER,

    -- Identifica o usuário responsável pelo produto.
    id_usuario INTEGER,

    -- Relaciona o produto à categoria.
    CONSTRAINT fk_produto_categoria
        FOREIGN KEY (id_categoria)
        REFERENCES categoria(id_categoria),

    -- Relaciona o produto ao usuário.
    CONSTRAINT fk_produto_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
)

-- =====================================================
-- 6. TABELA COMPOSICAO_PRODUTO
-- =====================================================

-- Armazena os insumos utilizados em cada produto.
-- Funciona como a composição ou receita do produto.
--
-- Exemplo:
-- Produto: Bolo de chocolate
-- Insumo: Farinha
-- Quantidade: 0,500 kg

CREATE TABLE composicao_produto (

    -- Identificador único da composição.
    id_composicao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,

    -- Quantidade de insumo utilizada.
    -- DECIMAL(10,3): permite três casas decimais.
    -- CHECK impede quantidades negativas.
    quantidade DECIMAL(10,3)
        CHECK (quantidade >= 0) NOT NULL,

    -- Identifica o produto da composição.
    id_produto INTEGER,

    -- Identifica o insumo utilizado.
    id_insumo INTEGER,

    -- Identifica a unidade de medida da quantidade.
    id_unidade INTEGER,

    -- Relaciona a composição ao produto.
    CONSTRAINT fk_composicao_produto
        FOREIGN KEY (id_produto)
        REFERENCES produto(id_produto),

    -- Relaciona a composição ao insumo.
    CONSTRAINT fk_composicao_insumo
        FOREIGN KEY (id_insumo)
        REFERENCES insumo(id_insumo),

    -- Relaciona a composição à unidade de medida.
    CONSTRAINT fk_composicao_unidade
        FOREIGN KEY (id_unidade)
        REFERENCES unidade_medida(id_unidade)
)


-- =====================================================
-- 7. ADICIONAR CAMPO ATIVO
-- =====================================================

-- ALTER TABLE: modifica uma tabela existente.
-- ADD: adiciona um novo campo.
--
-- ATIVO controla se o usuário pode acessar o sistema.
--
-- 1 = usuário ativo.
-- 0 = usuário inativo.
--
-- DEFAULT 1: novos registros recebem 1 por padrão.
-- NOT NULL: o campo não pode ficar nulo.

ALTER TABLE USUARIO
ADD ATIVO INTEGER DEFAULT 1 NOT NULL


-- =====================================================
-- 8. ADICIONAR CAMPO TENTATIVAS_LOGIN
-- =====================================================

-- Armazena a quantidade de tentativas incorretas.
--
-- DEFAULT 0: o contador começa em zero.
--
-- No Python, após três erros:
-- TENTATIVAS_LOGIN recebe 3.
-- ATIVO recebe 0.
--
-- Assim, o usuário fica impedido de fazer login.

ALTER TABLE USUARIO
ADD TENTATIVAS_LOGIN INTEGER DEFAULT 0 NOT NULL

-- =====================================================
-- 9. TABELA HISTORICO_SENHA
-- =====================================================

-- Armazena os hashes das senhas anteriores.
--
-- É utilizada para impedir que o usuário reutilize
-- suas três últimas senhas.
--
-- A verificação das três senhas é feita no Python,
-- utilizando SELECT FIRST 3 e Bcrypt.

CREATE TABLE HISTORICO_SENHA (

    -- Identificador único do registro de histórico.
    id_historico INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,

    -- Identifica o usuário que alterou a senha.
    id_usuario INTEGER NOT NULL,

    -- Armazena o hash da senha anterior.
    senha VARCHAR(254) NOT NULL,

    -- Relaciona o histórico ao usuário.
    CONSTRAINT fk_historico_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
)


-- =====================================================
-- 10. REATIVAR USUÁRIO
-- =====================================================

-- UPDATE: modifica registros existentes.
--
-- ATIVO = 1: reativa o usuário.
-- TENTATIVAS_LOGIN = 0: zera as tentativas.
--
-- WHERE: define qual usuário será atualizado.
-- Neste exemplo, será o usuário de ID 5.

UPDATE USUARIO
SET ATIVO = 1,
    TENTATIVAS_LOGIN = 0
WHERE ID_USUARIO = 5


-- =====================================================
-- 11. CONSULTAR SITUAÇÃO DOS USUÁRIOS
-- =====================================================

-- SELECT: consulta os registros da tabela.
-- Permite verificar se o usuário está ativo
-- e quantas tentativas incorretas possui.

SELECT
    ID_USUARIO,
    NOME,
    EMAIL,
    ATIVO,
    TENTATIVAS_LOGIN
FROM USUARIO
